### ISSUE TITLE
New links for those channels

### ISSUE THREAD

**Issue by spotanjo3** [bebawy6/EPG#11]
Here:

BET WEST (PACIFIC) ----- https://streamingtvguides.com/Channel/BETP
ActionMAX WEST (PACIFIC) ----- https://streamingtvguides.com/Channel/ACMAXP
MoreMAX WEST (PACIFIC) ----- https://www.tvpassport.com/tv-listings/stations/moremax-pacific-hd/8472
OuterMAX EAST ----- https://streamingtvguides.com/Channel/OMAXHD
ThrillerMAX WEST (PACIFIC) ----- https://www.tvpassport.com/tv-listings/stations/thrillermax-pacific/2595
Catchy Comedy Network ---- https://www.tvpassport.com/tv-listings/stations/catchy-comedy-network/15640
Discovery Channel WEST (PACIFIC) ----- https://streamingtvguides.com/Channel/DSCP
Discovery Science EAST ------ https://streamingtvguides.com/Channel/SCIHD
Disney Junior East ----- https://streamingtvguides.com/Channel/DJCHHD
Disney XD EAST ------ https://streamingtvguides.com/Channel/DXDHD
Disney XD WEST (PACIFIC) ------ https://streamingtvguides.com/Channel/DXDHDP

Bravo West (PACIFIC) ----- https://streamingtvguides.com/Channel/BRAVOP
FAIL ARMY ------ https://www.tvpassport.com/series/fail-army/289437
FX NETWORK WEST (PACIFIC) ------ https://streamingtvguides.com/Channel/FXPHD
HBO 2 WEST (PAFCIFIC) ------ https://streamingtvguides.com/Channel/HBO2PHD
HBO COMEDY WEST (PACIFIC) ------- https://streamingtvguides.com/Channel/HBOCP
HBO FAMILY WEST (PACIFIC) ------ https://www.tvpassport.com/tv-listings/stations/hbo-family-pacific-feed/1216
HBO SIGNATURE WEST (PACIFIC) ------- https://streamingtvguides.com/Channel/HBOSIGP
HBO ZONE WEST (PACIFIC) ------- https://streamingtvguides.com/Channel/HBOZP
HGTV WEST (PACIFIC) ------- https://streamingtvguides.com/Channel/HGTVPHD
NHK WORLD ----- https://www.tvpassport.com/tv-listings/stations/nhk-world-kcetdt4-los-angeles-ca/11276

**Comment by bebawy6** [comment]
duplicate

**Comment by spotanjo3** [comment]
Thank you for the duplicate. Have you finished them so I can test them  on my TV ?

**Comment by spotanjo3** [comment]
Hi. I am still waiting. Can you adding them so I can test and report to you ? Please ?

**Comment by spotanjo3** [comment]
@bebawy6 I hope you had a good time yesterday. And have you added them yet ?

**Comment by spotanjo3** [comment]
I can't wait. If everything is according to the properly schedule then I will gladly adding some more to complete your aweoms EPG. Thanks.

**Comment by bebawy6** [comment]
completed
