### ISSUE TITLE
5 errors links found plus you forgot one - replace the right ones

### ISSUE THREAD

**Issue by spotanjo3** [bebawy6/EPG#14]
Good news. Most worked fine and schedule is properly now. GOOD WORK! 

However, I found tvpassports have some issues - Four error links.

I replace those correct links is streamingtvguides because it seems to work the best:  Can you replace them ?

Please replace the right ones: 

NHK WORLD - https://streamingtvguides.com/Channel/NHKWRLD

5 STAR MAX WEST PACIFIC - https://www.tvpassport.com/tv-listings/stations/5-star-max-pacific/2627

HBO FAMILY WEST (PACIFIC) - https://streamingtvguides.com/Channel/HBOF

ThrillerMax West (PACIFIC) - https://streamingtvguides.com/Channel/THMAXP

MoreMax WEST (PACIFIC) - https://streamingtvguides.com/Channel/MMAXPHD

**You forgot to added FAIL ARMY** ------ https://www.tvpassport.com/series/fail-army/289437

**Comment by spotanjo3** [comment]
Hi, It have been 2 days now. I hope you didnt forgot it. ^_^

**Comment by spotanjo3** [comment]
Are you okay ? I hope everything is okay with you. I am still waiting for those 4 links to be replaced and fixed.

**Comment by bebawy6** [comment]
I appreciate your interest in the EPG I maintain for personal use. While I understand your enthusiasm for modifications, I want to clarify that this project is something I do as a hobby during my spare time. My family, two jobs, and personal commitments take up the majority of my time, making it challenging for me to accommodate frequent modifications.

However, I strive to update the EPG whenever I can find some spare time, and I'll consider your suggestions for future updates. I hope you understand the constraints I face and appreciate your patience and support.

**Comment by spotanjo3** [comment]
I understand. No problem. For now, are you going to fix those ? 

How do I know if you will let me adding more epg links for you, I wonder? ^_^;

**Comment by bebawy6** [comment]
Thank you for understanding the time constraints I have. I appreciate your willingness to contribute and add more EPG links. While I cannot guarantee immediate implementation, you can certainly suggest new links for consideration. However, please keep in mind that any additions or modifications will be done in my spare time, without any pressure or strict deadlines.

Regarding your current request, I'll make an effort to address it before the weekend. However, please note that unforeseen circumstances may affect the timeline.

**Comment by spotanjo3** [comment]
Okay, I will open a new one and leave few more EPGs soon for you to adding it but only to your spare time, I understand. So I wont bother you until you have spare time to do so.

**Comment by spotanjo3** [comment]
> **Regarding your current request, I'll make an effort to address it before the weekend.** However, please note that unforeseen circumstances may affect the timeline.

Hi. Please let me know when you are complete this one. 

So the next links will be ready soon but only according to your spare time, I know. ^_^

**Comment by bebawy6** [comment]
ready

**Comment by spotanjo3** [comment]
Thank you but are you sure you added MoreMax WEST (PACIFIC) - https://streamingtvguides.com/Channel/MMAXPHD? It wasnt on my list but everything else worked.

**Comment by bebawy6** [comment]
yes

**Comment by spotanjo3** [comment]
> yes

1 link is dead. Replace a link.

Here:

MoreMax West (Pacific) - https://www.tvpassport.com/tv-listings/stations/moremax-pacific-hd/8472

**Comment by spotanjo3** [comment]
Did you fixed MoreMax West West (Pacific) tv passport 8472 ? 

I will not a new links until next month to give you a break. ^_^

**Comment by bebawy6** [comment]
Yes

**Comment by spotanjo3** [comment]
Hello. MoreMax West (Pacific) TV Passport 8472 is working. Thank you.

 I found that MoreMax for Eastern TV Passport is wrong. Somehot it was double schedule like Pacific, lol. My apology:

MoreMax East - https://www.tvpassport.com/tv-listings/stations/moremax-eastern-hd/7097

**Comment by spotanjo3** [comment]
Have you fixed MoreMax Eastern link yet ?

HBO FAMILY WEST PACIFIC correct linK: https://streamingtvguides.com/Channel/HBOFHD

**Comment by spotanjo3** [comment]
I didnt added new links just yet. This need to fixed. Can you please fix it ? I wont make a new links until September to give you more time. ^_^

Please say yes if you already fixed one link and added "miss" link I requested before.

**Comment by bebawy6** [comment]
Yes completed

**Comment by spotanjo3** [comment]
I noticed that you missed two:

 5 Star Max WEST (Paciific)

https://www.tvpassport.com/tv-listings/stations/5-star-max-pacific/2627

MoreMax WEST (Pacific:)

https://streamingtvguides.com/Channel/MMAXPHD
