### ISSUE TITLE
All epg stop

### ISSUE THREAD

**Issue by Shawkiiz** [bebawy6/EPG#17]
Hay bro 
All epg are stop , and no information for all channel's

**Comment by bebawy6** [comment]
Hello,

I encountered a problem with my computer. It experienced a crash four days ago, leading to the loss of some of the automation scripts I had created. Additionally, my aging PC, which operates continuously 24/7, continues to experience frequent crashes. Consequently, this has disrupted the functioning of my scripts and processes. I used the long weekend to work on it, hoping that the problem will be resolved within the coming hour.
