### ISSUE TITLE
OSN Arabic EPG Titles

### ISSUE THREAD

**Issue by boeder9** [bebawy6/EPG#18]
Hey buddy,

Sorry to bug you again.

OSN Channels finally have data so thanks for that. But apparently the Alfa and Arabic OSN channels no longer have titles in Arabic, they are in English which is confusing and a bit annoying.

So I wanted to request if you can have an Arabic variant for the below channels or just switch them to Arabic as these are Arabic channels anyway, here are the channels that require this edit:

OSN Alfa Cinema 1
OSN Alfa Cinema 2
OSN Alfa Musalsalat 1
OSN Alfa Musalsalat 2
OSN Al Safwa
OSN Alfa AlYoum
OSN Music Now
OSN Yahala
OSN Yahala Aflam
OSN Yahala Bil Arabi
OSN ART Aflam 1
OSN ART Aflam 2
OSN ART Cinema
OSN ART Hekayat 1
OSN ART Hekayat 2

The source for EPG is https://www.osn.com/ar-sa/watch/tv-schedule

The rest are fine.

Again no rush on this, thank you so much brother!

**Comment by bebawy6** [comment]
will check with webgraber as they encrypt the ini file we use

**Comment by boeder9** [comment]
OK, brilliant, thanks!

**Comment by boeder9** [comment]
@bebawy6 I checked the .xml and there are two title lines, one for Arabic and one for English

<title lang="ar">TITLE IN ARABIC</title>
<title lang="en">TITLE IN ENGLISH</title>

Tivimate chooses English and I dont think that's an option to change. Maybe for the channels I listed the title in the xml should be in Arabic only.

**Comment by bebawy6** [comment]
You correct that is the solution working on

**Comment by boeder9** [comment]
Works perfectly now! Big thanks!

**Comment by bebawy6** [comment]
Glad to hear it.
