### ISSUE TITLE
New channels 👍🏻

### ISSUE THREAD

**Issue by Shawkiiz** [bebawy6/EPG#20]
Hay bro ,
Thx for adding Islamic channels 🥰

Because you are the best, I would like to suggest some new channels for you to add 

- mbc althaqafya
- alshams 
- watan
- al sharq documentary
- al majd documentary 
- shahid aflam
- shahid action
- shahid almalab

- mawada
- al maaly
- al fath
- zad
- al erth al nbawi
- safa
- peace tv

- extra live
- mekamleen
- al hiwar 
- news 9
- al haqiqa al dawliah
- mbc persia
- osn vh
- osn ginx eSports
- al ghad (update logo)
-  nile news (update logo)
-  mbc elife (no logo)
- alhayat drama (no data)
- (General logo for movies channels)
- (general logo for play show channels)
- (General logo for news channels)

**Comment by Shawkiiz** [comment]
Hay bro ,

**Comment by bebawy6** [comment]
Partially finished based on the availability of channels.
