### ISSUE TITLE
New channel's suggestions 👍🏻

### ISSUE THREAD

**Issue by Shawkiiz** [bebawy6/EPG#22]
- extra live
- Al Arabia Business
- kid zone max
- smart zone
- spacetoon
- Al Sharq Discovery

- UPDATE  : Al hayat Drama logo
- UPDATE  : All panorama Channels logo 
- ADD general logo for kids channels 
- ADD general logo for islamic channels

Thx a lot bro 🌹

**Comment by bebawy6** [comment]
Please provide the requested logo 'high quality and transparent'

**Comment by Shawkiiz** [comment]
![Extra Live](https://github.com/bebawy6/EPG/assets/119056903/094e7ee3-ffbd-418b-ac77-b7e92e035a9e)
![islamic logo_1](https://github.com/bebawy6/EPG/assets/119056903/25e8f76e-0d12-4c0b-ba75-da0b08c44f05)
![islamic logo_2](https://github.com/bebawy6/EPG/assets/119056903/a0ded003-9b46-42ed-8e0c-75695e4ff13c)
![kids channels logo](https://github.com/bebawy6/EPG/assets/119056903/b3edac33-3185-4e7c-94b4-ef159295f0ed)
![ElSharq News](https://github.com/bebawy6/EPG/assets/119056903/a229bfd9-cd9a-4d8d-a28c-3f96ff143a41)
![Spacetoon](https://github.com/bebawy6/EPG/assets/119056903/da168492-6c18-46f9-bed9-bdff8921dcc4)
![SmartZone](https://github.com/bebawy6/EPG/assets/119056903/742fca47-696d-4258-93b9-5afed2fb7a33)
![Kid Zone Max](https://github.com/bebawy6/EPG/assets/119056903/eb96efa2-cfdf-4d5b-9811-28233ffb1ad9)
![Kid Zone](https://github.com/bebawy6/EPG/assets/119056903/5929ed04-053d-4f8b-a8da-51d32e7a2166)
![AL-ARABIYA-BUSINESS-LOGO-1-768x327](https://github.com/bebawy6/EPG/assets/119056903/65fafff1-d595-42d3-852c-554e8587f311)
![Alsharq Discovery](https://github.com/bebawy6/EPG/assets/119056903/3cc281c9-c409-4126-b32c-2690036951db)

**Comment by Shawkiiz** [comment]
![Movie logo 01](https://github.com/bebawy6/EPG/assets/119056903/345dad7c-5372-4625-b675-2578838dd0af)
![Netflix N](https://github.com/bebawy6/EPG/assets/119056903/245ff3a1-48c2-4133-99b2-d2e16dcedc98)
![Netflix](https://github.com/bebawy6/EPG/assets/119056903/27494a9e-9701-4879-b8f1-25cb418cf0e5)
![Movie logo 02](https://github.com/bebawy6/EPG/assets/119056903/66309adf-3cd8-4e63-980e-32a648c2e2e3)
![Movie logo 03](https://github.com/bebawy6/EPG/assets/119056903/2c4ecf84-59d1-45eb-b293-aabbc7308c06)
![TV General Logo](https://github.com/bebawy6/EPG/assets/119056903/9b32c059-7c8c-4a8d-b4e6-ae48065d4b1d)
![Nogoum FM](https://github.com/bebawy6/EPG/assets/119056903/db3e64bb-d377-40dd-a133-ffae917ddf99)

**Comment by Shawkiiz** [comment]
Thank bro for what has been added 🌹

But you didn't add (extra live & spacetoon & movie club & smart zone & kid zone & kide zone max & tv logo) 
I have already attached logos
