### ISSUE TITLE
New channel's logo 🌹

### ISSUE THREAD

**Issue by Shawkiiz** [bebawy6/EPG#23]
![Marvel](https://github.com/bebawy6/EPG/assets/119056903/865dd894-4492-4c9f-a205-0abf0f07d079)

![DC](https://github.com/bebawy6/EPG/assets/119056903/ab8028f2-30ae-495a-9971-00576a551265)

![HBO](https://github.com/bebawy6/EPG/assets/119056903/7f230fc8-c7b5-4c05-8df2-0527ae838dd7)

![Disney](https://github.com/bebawy6/EPG/assets/119056903/d7b35ca6-1dd1-4309-8700-64f6dce9be23)

![Shahid](https://github.com/bebawy6/EPG/assets/119056903/9dcb22e7-b6f6-4839-b3b0-1e2a5b73ee87)

![AlMajd](https://github.com/bebawy6/EPG/assets/119056903/6ee932b2-c7b0-4227-a7db-f3005b697f32)

![AlMajd Document](https://github.com/bebawy6/EPG/assets/119056903/bdd409b5-0bbf-4282-aecf-9b0cf9753ad3)

![AlMajd News](https://github.com/bebawy6/EPG/assets/119056903/f275b25f-356f-4a7b-9ff1-d7645fb1d17b)

![Majid](https://github.com/bebawy6/EPG/assets/119056903/2629a72d-3bdc-4d0b-b414-c8ff0c10cd31)

![AlMajd Hadeth](https://github.com/bebawy6/EPG/assets/119056903/a7fc697f-2c93-44bb-8410-1856fe953763)

![Zad](https://github.com/bebawy6/EPG/assets/119056903/cac2a154-6908-4a50-a767-2fbaf7b1a01b)

![AlMaaly](https://github.com/bebawy6/EPG/assets/119056903/51681f1f-3581-45f3-92ed-17a431cdb1ce)

![Art_Network](https://github.com/bebawy6/EPG/assets/119056903/12e84594-a491-4bbd-811e-da8071afb029)

**Comment by bebawy6** [comment]
http://www.webgrabplus.com/
https://youtu.be/Izgt8A808zU?si=lpPRW0hKwU1LUkYo

**Comment by Shawkiiz** [comment]
What is this pro ?

> http://www.webgrabplus.com/ https://youtu.be/Izgt8A808zU?si=lpPRW0hKwU1LUkYo


What is this bro ?

**Comment by Shawkiiz** [comment]
> http://www.webgrabplus.com/ https://youtu.be/Izgt8A808zU?si=lpPRW0hKwU1LUkYo

Could you plz add them bro coz i don't know how to use this 🙏🏻
