### ISSUE TITLE
Logos Disappered 

### ISSUE THREAD

**Issue by boeder8** [bebawy6/EPG#3]
Hello,

The channel logos disappeared yesterday on my Tivimate even though I refreshed the epg just now.

**Comment by bebawy6** [comment]
Hello, This is will be setting in Tivimate,
1st:
go to setting >> Appearance >> Logos >> logos priority  select preferred logos from EPG. 
if it did not work
2nd:
go to setting >> Playlists >> click on your playlist name >> logos priority >> select preferred logos from EPG.

and let me now if it fixes your issue. Thanks

**Comment by boeder8** [comment]
> Hello, This is will be setting in Tivimate, 1st: go to setting >> Appearance >> Logos >> logos priority select preferred logos from EPG. if it did not work 2nd: go to setting >> Playlists >> click on your playlist name >> logos priority >> select preferred logos from EPG.
> 
> and let me now if it fixes your issue. Thanks

Thanks. This is already enabled and the logos were working fine, they just disappeared yesterday.

I'll try to clear the cache tomorrow.

**Comment by boeder8** [comment]
I tried clearing cache and the same problem continues. It is only with logos from your awesome .xml, the epg works but the logos stopped appearing since yesterday.

**Comment by boeder8** [comment]
I opened VPN and your logos instantly loaded. Seems like my ISP is blocking the URL. The issue is resolved.

**Comment by bebawy6** [comment]
many thanks for the update
