### ISSUE TITLE
Request: OSN and Shahid

### ISSUE THREAD

**Issue by boeder8** [bebawy6/EPG#4]
Hello mate,

First off, thanks for making the best epg guide available! I appreciate your work!

I have a few requests regarding OSN and Shahid

1. Making two seperate XMLs for OSN: 1x Arabic 1 EPG and 1x English EPG as some channels on OSN are more appropriate to have Arabic EPGs, others need English EPGs. Or perhaps same XML just adding suffix _ar or _en.

Sources:

osn.com/ar-sa/watch/tv-schedule

osn.com/en-sa/watch/tv-schedule

2. Adding 1 missing channel in OSN:

OSN Moonbug Kids

3. Adding Shahid VIP channels (EPG in Arabic) e.g.

Tash
Almasrah
Nojoum
Hassino
Khaleeji
Bollywood
Turki
Masr
Aloustoura
Al Zaeem
Levent
Tareekhi
Al Sham
Maqaleb
Comedy
The Chef
Shahid Aloula
Mawaheb
Style
Korean

I guess you can find more info from the shahid xml and ini here: https://github.com/SilentButeo2/webgrabplus-siteinipack/tree/master/siteini.pack/Saudi%20Arabia

Thanks in advance and keep up the awesome work.

**Comment by bebawy6** [comment]
Your request may be complex to edit the original OSN ini file, I will do my best.

**Comment by boeder8** [comment]
> Your request may be complex to edit the original OSN ini file, I will do my best.

Yes, I understand. Thank you so very much!

**Comment by bebawy6** [comment]
Hey, what TV provider do you use? I'm thinking about switching mine and wanted to get some recommendations

**Comment by boeder8** [comment]
> The request has been completed, but please note that there may be some limitations as the source (Shahid web) does not have information about the new channels.

Awesome! Thanks so much, ill check it later :)

**Comment by boeder8** [comment]
> Hey, what TV provider do you use? I'm thinking about switching mine and wanted to get some recommendations

Bro I've been doing a lot of research and trial/error over the last 6 months. I now have several providers, no one provider is perfect. It depends what you're looking for

1. For Arabic channels OSN, beIN, Shahid etc I use a local provider called Hulk. He operates on WhatsApp.

2. For international channels (minus UK) I use IPTV-Secured

3. For UK and as a backup I also use Necroip.tv

4. For super FHD and UHD + raw feeds of foreign sport channels (mainly UK) I use PieTV, they operate from Telegram

I can link you to the above, depending on your needs.

**Comment by bebawy6** [comment]
Please email me at soash446@gmail.com and let's delete the last two comments.
